spring:
  datasource:
    url: jdbc:h2:mem:lecture;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
